dist: trusty
sudo: false

language: node_js
node_js:
  - '12.7.0'


cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers ChromeHeadless
  - npm run test:cover -- --watch=false --no-progress --browsers ChromeHeadless

after_success:
  - npm run coveralls
  - npm run build:gh-pages:demo1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: gh-pages
  on:
    branch: master
    branch: ghpagestravid