dist: trusty
sudo: false

language: node_js
node_js:
  - '12.7.0'


cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test:cover -- --single-run --no-progress --browers=ChromeHeadlessNoSandbox
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

  after_success:
    - npm run coveralls
