dist: trusty
sudo: false

language: node_js
node_js:
  - '12'


cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  
  - npm run test -- --single-run  --no-progress --browser=ChromeNoSandbox
  - npm run e2e --  --no-progress --config=protractor-ci.conf.js
